CI: compute/publish code coverage
Adds two jobs to the CI, which can be launched manually.

The test_coverage job launches the test suite (sequentially) and
generates an html report. The report artefact can be downloaded
from Gitlab CI web interface.

Alternatively, the pages job publishes this report on the static website
linked to the repo. It is accessible via a URL of the form

$CI_PAGES_URL/$CI_PIPELINE_ID

Examples:
    https://nomadic-labs.gitlab.io/tezos/105822404/
    https://tezos.gitlab.io/tezos/1234822404/

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,6 +9,8 @@ variables:
   ARTIFACT_DOWNLOAD_ATTEMPTS: "2"
 
 stages:
+  - test_coverage
+  - publish_coverage
   - doc
   - build
   - test
@@ -1216,3 +1218,85 @@ publish:doc:
         git commit -m "Import doc of ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}" ;
         git push origin master ;
       fi
+
+# This job publishes the html report generated by the coverage job.
+# It is accessible on the gitlab page associated to the project
+# via URL $CI_PAGES_URL/$CI_PIPELINE_ID
+#
+# for instance https://nomadic-labs.gitlab.io/tezos/${CI_PIPELINE_ID}
+# https://tezos.gitlab.io/tezos/${CI_PIPELINE_ID}
+#
+# It is run manually from the Gitlab CI interface.
+#
+# Note that this job is somewhat redundant. It is already possible to browse
+# the html report artefact generated by the test_coverage job.
+#
+
+pages:
+  when: manual
+  # The cache rule ensures public (i.e. the static website) isn't erased
+  # whenever we start a new pipeline
+  # https://docs.gitlab.com/ee/ci/caching/
+  # The pages job retrieves the old public dir from the cache, adds a new
+  # report, and publishes the new public dir.
+  cache:
+    paths:
+      - public
+  stage: publish_coverage
+  dependencies:
+    - test_coverage
+  script:
+    - mkdir -p public
+    - mv _coverage_report public/$CI_PIPELINE_ID
+    - echo "Coverage report published at $CI_PAGES_URL/$CI_PIPELINE_ID"
+  artifacts:
+    paths:
+      - public
+    # This is the minimum time the public artifact will remain available.
+    # Everytime a pages job is launched, this time period is reset
+    expire_in: 7 days
+
+############################################################
+## Stage: coverage                                        ##
+############################################################
+
+# This job is manual. It can be launched from the gitlab CI interface.
+# It instruments the code with bisect_ppx and runs the full test suite
+# (sequentially).
+
+test_coverage:
+  image: ${build_deps_image_name}:${build_deps_image_version}
+  stage: test_coverage
+  when: manual
+  variables:
+    # We exclude from coverage old protocols and code that can't be
+    # instrumented because of current limitations of bisect_ppx.
+    OLD_PROTOCOLS: "src/proto_000_Ps9mPmXa src/proto_001_PtCJ7pwo src/proto_002_PsYLVpVv src/proto_003_PsddFKi3 src/proto_004_Pt24m4xi src/proto_005_PsBABY5H src/proto_005_PsBabyM1 src/proto_006_PsCARTHA"
+    # TODO try with future version, didn't work with bisect_ppx 2.4.1
+    NOT_INSTRUMENTABLE: "src/lib_crypto"
+    COVERAGE_EXCLUDE: "$OLD_PROTOCOLS $NOT_INSTRUMENTABLE"
+  script:
+    - scripts/instrument_dune_bisect.sh src/ --except $COVERAGE_EXCLUDE
+    - make
+    # A failing test shouldn't prevent the generation of the report (|| true)
+    - dune build @runtest || true
+    - make -C tests_python all || true
+    - make coverage-report
+    - make coverage-report-summary
+    # hack to capture script success in after_script script
+    - touch $CI_PROJECT_DIR/__success
+  after_script:
+    - |
+      if [ ! -f __success ]; then
+        echo "Job was unable to generate the coverage report."
+        echo "Check http://tezos.gitlab.io/developer/testing.html#measuring-test-coverage"
+        echo "for a list of known issues."
+      fi
+  # This is for gitlab to extract the coverage summary and display it
+  # to the user as a badge.
+  coverage: '/Coverage: \d+\/\d+ \(([^%]+%)\)/'
+  artifacts:
+    when: always
+    paths:
+      - _coverage_report/
+    expire_in: 15 days
