CIAO: fix CI generation check

diff --git a/ci/makefile b/ci/makefile
--- a/ci/makefile
+++ b/ci/makefile
@@ -36,12 +36,12 @@ docker-remove-extra-files: docker-do-remove-extra-files # Build the target 'remo
 
 .PHONY: check
 check: # Used in the CI to verify that [.gitlab-ci.yml] is up to date.
-	@git diff --exit-code HEAD -- ../.gitlab-ci.yml || (echo "Cannot check generated [.gitlab-ci.yml] file, some changes are uncommitted"; exit 1)
+	@git diff --exit-code HEAD || (echo "Cannot check generated GitLab CI YAML files, some changes are uncommitted"; exit 1)
 	@$(MAKE) all
-	@git diff --exit-code HEAD -- ../.gitlab-ci.yml > /dev/null || ( \
+	@git diff --exit-code HEAD > /dev/null || ( \
 	  echo "Repository not clean after 'make -C ci'."; \
 	  echo "You should not edit generated GitLab CI .yml files directly."; \
-	  echo "Edit ci/bin/main.ml instead."; \
+	  echo "Edit the appropriate file(s) in ci/bin/ instead."; \
 	  echo "Then run 'make -C ci' and commit the difference."; \
 	  exit 1 \
 	)
